---
title: "Examples with {flextable}"
date: "`r format(Sys.time(), '%B %d, %Y')`"
knit: (function(inputFile, encoding) {
    rmarkdown::render(inputFile, 
    output_dir = here::here("outputs"))
     })
output:
  pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(palmerpenguins)
library(tidyverse)
library(flextable)
library(gtsummary)

data(penguins)

penguins <- penguins %>%
  bstfun::use_varnames_as_labels()

```

# Print a Plain Dataframe

```{r}
df <- penguins %>% 
  head(n =10)

df %>% flextable()

```


# {gtsummary} Examples

## Default Print Engine

Example where we don't specify print engine:

```{r}
penguins %>% 
  tbl_summary() %>%
  bold_labels() %>%
  italicize_levels()
```

## Specify Print Engine

```{r}
penguins %>% 
  tbl_summary() %>%
  bold_labels() %>%
  italicize_levels() %>%
  as_flex_table()
```

## With Compact Theme

```{r}
theme_gtsummary_compact()

penguins %>% 
  tbl_summary() %>%
  bold_labels() %>%
  italicize_levels() %>%
  as_flex_table()

reset_gtsummary_theme()
```

## Add Header

```{r}
penguins %>% 
  tbl_summary() %>%
  bold_labels() %>%
  italicize_levels()  %>%
  as_flex_table() %>%
  add_header_row(values = "Title", colwidths = 2)

```

<br>

## Add Footnotes 

```{r}

x <- penguins %>% 
  tbl_summary() %>%
  bold_labels() %>%
  italicize_levels() %>%
  as_flex_table() %>%
  footnote(., i = 1, j =1,
           value = as_paragraph("Custom Footnote"))

```

## Highlight Specific Values

```{r}

```


## Merged Tables with Spanning Headers

```{r}
sum <- penguins %>%
  select(species, island, sex) %>%
  tbl_summary(by = species) %>%
  add_p()


reg <- glm(species ~ island + sex, family = binomial(), data = penguins)

reg <- reg %>%
  tbl_regression()

tbl_merge(list(sum, reg),
          tab_spanner = c("**Summary Statistics**", "**Regression***")) %>% 
  
  as_flex_table()

```

# Saving Quickly 

