---
title: "Examples with {gt}"
date: "`r format(Sys.time(), '%B %d, %Y')`"
knit: (function(inputFile, encoding) {
    rmarkdown::render(inputFile, 
    output_dir = here::here("outputs"))
     })
output:
  pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(palmerpenguins)
library(tidyverse)
library(gtsummary)
library(labelled)
library(gt)

data(penguins)

penguins <- penguins %>%
  bstfun::use_varnames_as_labels()

```

# Print a Plain Dataframe 

```{r}
df <- penguins %>% 
  head(n =10)

df %>% gt()

```


# {gtsummary} Examples

## Default Print Engine

Example where we don't specify print engine:

```{r}
penguins %>% 
  tbl_summary() %>%
  bold_labels() %>%
  italicize_levels()
```

## Specify Print Engine

```{r}
penguins %>% 
  tbl_summary() %>%
  bold_labels() %>%
  italicize_levels() %>%
  as_gt()
```

# With Compact Theme

```{r}
theme_gtsummary_compact()

penguins %>% 
  tbl_summary() %>%
  bold_labels() %>%
  italicize_levels() %>%
  as_gt()

reset_gtsummary_theme()
```

## Add Header

```{r}
penguins %>% 
  tbl_summary() %>%
  bold_labels() %>%
  italicize_levels()  %>%
  as_gt() %>%
  tab_header("Title")

```


## Add Footnotes 

```{r}

x <- penguins %>% 
 tbl_summary() %>%
 bold_labels() %>%
 italicize_levels()  %>%
 as_gt() 

# To inspect internals of gt object you can do:
#x$`_data`

x %>%
  tab_footnote(
    footnote = "Custom Footnote",
    locations = cells_column_labels(
      columns = label
    ))

```

# Highlight Specific Values

```{r}
x <- penguins %>% 
  tbl_summary() %>%
  bold_labels() %>%
  italicize_levels()  %>%
  as_gt() %>%
  tab_header("Title")
```


```{r}
x$`_data` <- x$`_data` %>%
  mutate(new_cond = parse_number(stat_0)) 

x %>%
      gt::tab_style(
        style = list(
          cell_fill(color = "purple")
          ),
        locations = cells_body(
          columns = stat_0,
          rows =  new_cond >= 100 
        )
      )


```


```{r, eval = FALSE}
x %>%
  mutate(new_cond = parse_number(stat_0)) %>%
  set_text_color(row = .$new_cond >= 100, 2,  "purple") %>%
  select(-new_cond)
```

## Merged Tables with Spanning Headers

```{r}
sum <- penguins %>%
  select(species, island, sex) %>%
  tbl_summary(by = species) %>%
  add_p()


reg <- glm(species ~ island + sex, family = binomial(), data = penguins)

reg <- reg %>%
  tbl_regression()

tbl_merge(list(sum, reg),
          tab_spanner = c("**Summary Statistics**", "**Regression***")) %>% 
  
  as_gt()

```

# Saving Quickly 
